import mongoose, { Types } from "mongoose";
import { env } from "../../zod/envSchema";
import ShortcutModel from "../models/ShortcutModel";

const macShortcuts = [
  {
    _id: new Types.ObjectId(),
    shortDescription: "Copy",
    description: "Copy selected item to clipboard",
    keys: ["cmd", "c"],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Paste",
    description: "Paste item from clipboard",
    keys: ["cmd", "v"],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Cut",
    description: "Cut selected item to clipboard",
    keys: ["cmd", "x"],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Select All",
    description: "Select all items",
    keys: ["cmd", "a"],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Save",
    description: "Save current document",
    keys: ["cmd", "s"],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Find",
    description: "Find items in current document",
    keys: ["cmd", "f"],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "New Window",
    description: "Open a new window",
    keys: ["cmd", "n"],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Close Window",
    description: "Close current window",
    keys: ["cmd", "w"],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Switch Apps",
    description: "Switch between open applications",
    keys: ["cmd", "Tab"],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Force Quit",
    description: "Open force quit applications window",
    keys: ["cmd", "option", "Escape"],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Screenshot",
    description: "Take a screenshot of selected area",
    keys: ["cmd", "shift", "4"],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Full Screenshot",
    description: "Take a screenshot of entire screen",
    keys: ["cmd", "shift", "3"],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Spotlight Search",
    description: "Open Spotlight search",
    keys: ["cmd", "space"],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Minimize Window",
    description: "Minimize current window to dock",
    keys: ["cmd", "m"],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Undo",
    description: "Undo last action",
    keys: ["cmd", "z"],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Lock Screen",
    description: "Lock your computer screen quickly",
    keys: ["cmd", "ctrl", "q"],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Mission Control",
    description: "Show all open windows and desktops",
    keys: ["ctrl", "ArrowUp"],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Application Windows",
    description: "Show all windows of current application",
    keys: ["ctrl", "ArrowDown"],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Quick Look",
    description: "Preview selected item",
    keys: ["space"],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Open Preferences",
    description: "Open preferences/settings of current application",
    keys: ["cmd", ","],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Hide Application",
    description: "Hide windows of current application",
    keys: ["cmd", "h"],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Hide Others",
    description: "Hide all other applications",
    keys: ["cmd", "option", "h"],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Emoji Picker",
    description: "Open emoji and symbol picker",
    keys: ["cmd", "ctrl", "space"],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Switch Desktop",
    description: "Switch between desktops/spaces",
    keys: ["ctrl", "ArrowRight"],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "File Info",
    description: "Show file information in Finder",
    keys: ["cmd", "i"],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "New Folder",
    description: "Create a new folder in Finder",
    keys: ["cmd", "shift", "n"],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Delete File",
    description: "Move selected item to trash",
    keys: ["cmd", "Backspace"],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Empty Trash",
    description: "Empty the trash with confirmation",
    keys: ["cmd", "shift", "Backspace"],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Print",
    description: "Open print dialog",
    keys: ["cmd", "p"],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Find Files",
    description: "Open Finder search",
    keys: ["cmd", "option", "space"],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Show Downloads",
    description: "Open Downloads folder",
    keys: ["cmd", "option", "l"],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Select Address Bar",
    description: "Select the address/search bar in Finder or browser",
    keys: ["cmd", "l"],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Show Path Bar",
    description: "Toggle path bar in Finder",
    keys: ["cmd", "option", "p"],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Zoom In",
    description: "Increase view size",
    keys: ["cmd", "="],
    type: "mac",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Zen Mode",
    description: "Toggle distraction-free full screen mode",
    keys: ["cmd", "k", "z"],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Change Language",
    description: "Change file language/syntax",
    keys: ["cmd", "k", "m"],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "New File",
    description: "Create new file",
    keys: ["cmd", "n"],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Save All",
    description: "Save all open files",
    keys: ["cmd", "option", "s"],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Go to File",
    description: "Jump to a specific line number",
    keys: ["Control", "g"],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Replace",
    description: "Open find and replace",
    keys: ["cmd", "option", "f"],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Indent Line",
    description: "Indent current line",
    keys: ["cmd", "]"],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Outdent Line",
    description: "Outdent current line",
    keys: ["cmd", "["],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Toggle Word Wrap",
    description: "Turn line wrapping on/off",
    keys: ["option", "z"],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Show Problems",
    description: "Toggle problems/errors panel",
    keys: ["cmd", "shift", "m"],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Go Back",
    description: "Navigate to previous location",
    keys: ["ctrl", "-"],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Go Forward",
    description: "Navigate to next location",
    keys: ["ctrl", "shift", "-"],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Toggle Panel",
    description: "Show/hide bottom panel",
    keys: ["cmd", "j"],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Open Settings",
    description: "Open VS Code settings",
    keys: ["cmd", ","],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Fold Region",
    description: "Fold code region",
    keys: ["cmd", "option", "["],
    type: "vs code",
  },
];

const vsCodeShortcuts = [
  {
    _id: new Types.ObjectId(),
    shortDescription: "command Palette",
    description: "Open command palette to access all commands",
    keys: ["cmd", "shift", "p"],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Quick Open",
    description: "Quickly open files in workspace",
    keys: ["cmd", "p"],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Remove and Organise Imports",
    description: "Remove unused imports and sort them",
    keys: ["option", "shift", "o"],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Toggle Sidebar",
    description: "Show or hide the sidebar",
    keys: ["cmd", "b"],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Select Matching Text",
    description: "Select text that matches current selection",
    keys: ["cmd", "d"],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Undo Selected Instance",
    description: "Unselect the last selected instance of text",
    keys: ["cmd", "u"],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Select All Matching Text",
    description: "Select all matching instances of current selection",
    keys: ["cmd", "shift", "l"],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Toggle Terminal",
    description: "Show or hide integrated terminal",
    keys: ["cmd", "`"],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Find in File",
    description: "Search within current file",
    keys: ["cmd", "f"],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Find in Workspace",
    description: "Search across all files in workspace",
    keys: ["cmd", "shift", "f"],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Multi Cursor",
    description: "Add additional cursors for editing",
    keys: ["option", "cmd", "ArrowDown"],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Copy Line",
    description: "Copy current line up or down",
    keys: ["shift", "option", "ArrowDown"],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Move Line",
    description: "Move current line up or down",
    keys: ["option", "ArrowDown"],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Comment Line",
    description: "Toggle line comment",
    keys: ["cmd", "/"],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Block Comment",
    description: "Toggle block comment",
    keys: ["shift", "option", "a"],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Go to Definition",
    description: "Jump to definition of symbol under cursor",
    keys: ["F12"],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Peek Definition",
    description: "Preview definition without leaving current location",
    keys: ["option", "F12"],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Format Document",
    description: "Format entire document",
    keys: ["shift", "option", "f"],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Quick Fix",
    description: "Show code actions and quick fixes",
    keys: ["cmd", "."],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Rename Symbol",
    description: "Rename all occurrences of symbol",
    keys: ["F2"],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Select All Occurrences",
    description: "Select all occurrences of current selection",
    keys: ["cmd", "shift", "l"],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Open Preview",
    description: "Open markdown preview",
    keys: ["cmd", "shift", "v"],
    type: "vs code",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Close Editor",
    description: "Close current editor tab",
    keys: ["cmd", "w"],
    type: "vs code",
  },
];

const terminalShortcuts = [
  {
    _id: new Types.ObjectId(),
    shortDescription: "Clear Terminal",
    description: "Clear the terminal screen",
    keys: ["ctrl", "l"],
    type: "terminal",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "End of Line",
    description: "Move cursor to end of line",
    keys: ["ctrl", "e"],
    type: "terminal",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Start of Line",
    description: "Move cursor to start of line",
    keys: ["ctrl", "a"],
    type: "terminal",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Delete Line",
    description: "Delete entire line",
    keys: ["ctrl", "u"],
    type: "terminal",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Delete Word",
    description: "Delete word before cursor",
    keys: ["ctrl", "w"],
    type: "terminal",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Search History",
    description: "Search through command history",
    keys: ["ctrl", "r"],
    type: "terminal",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Next Command",
    description: "Go to next command in history",
    keys: ["ctrl", "n"],
    type: "terminal",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Previous Command",
    description: "Go to previous command in history",
    keys: ["ctrl", "p"],
    type: "terminal",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Clear Screen Forward",
    description: "Clear the screen from cursor forward",
    keys: ["ctrl", "k"],
    type: "terminal",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Interrupt Process",
    description: "Stop/interrupt current process",
    keys: ["ctrl", "c"],
    type: "terminal",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Exit Terminal",
    description: "Exit current terminal session",
    keys: ["ctrl", "d"],
    type: "terminal",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Word Forward",
    description: "Move cursor forward one word",
    keys: ["option", "f"],
    type: "terminal",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Word Backward",
    description: "Move cursor backward one word",
    keys: ["option", "b"],
    type: "terminal",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Clear Word Forward",
    description: "Delete word after cursor",
    keys: ["option", "d"],
    type: "terminal",
  },
  {
    _id: new Types.ObjectId(),
    shortDescription: "Paste Last Argument",
    description: "Paste last argument from previous command",
    keys: ["option", "."],
    type: "terminal",
  },
];

async function seedDB() {
  try {
    await mongoose.connect(env.MONGO_URL);

    await ShortcutModel.deleteMany({
      type: { $in: ["mac", "vs code", "terminal"] },
    });

    await ShortcutModel.insertMany([
      ...macShortcuts,
      ...vsCodeShortcuts,
      ...terminalShortcuts,
    ]);

    console.log("Shortcuts seeded successfully!");
  } catch (error) {
    console.error("Error seeding database:", error);
  } finally {
    await mongoose.connection.close();
  }
}

seedDB();
